### ISSUE TITLE
Building Bunnimage: The Frontend

### ISSUE THREAD

**Issue by ganning127** [ganning127/test235#2]
Week 4 Step 1 ⬤◯◯◯◯◯◯ | 🕐 Estimated completion: 20-25 minutes

#### Demo: [🐰](https://week4step1.emilychen10.repl.co/)
*Congrats! If you made it this far, your Azure functions can now return data. However, users won't want to make POST requests with Postman to use your API though, so let's make it more user friendly.*

<p align="center">
   <img src="https://user-images.githubusercontent.com/69332964/121591478-8b903e00-ca07-11eb-87a3-e5c04d23086d.png" width="500" height="250" />
</p>

### ✅  Task:
- [ ]  Create a `bunnimage-frontend` branch 
- [ ]  Install [LiveServer](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) for testing
- [ ]  *Optional* Learn HTML basics with the [interactive course](https://lab.github.com/githubtraining/introduction-to-html)
- [ ]  Write JavaScript to listen for the form to be submitted and call a function
- [ ]  Write a function in `index.js` to display `input` appended with a ❤️ in the `output` div
- [ ] Commit your code to `bunnimage/index.html` and `bunnimage/script.js`
- [ ] Create a pull request that merges `bunnimage-frontend` to `main`, but **do not merge it**

### 🚧 Test your Work
Use **[LiveServer](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)**! This is a helpful VSCode extension that allows you to see your HTML that updates while you edit it.

<details>
<summary>:question: How do you use LiveServer? </summary>
<br>

![image](https://user-images.githubusercontent.com/69332964/99007366-0fd21f80-2512-11eb-9af9-311d89098c0b.png)
* To start a local server, click `Go live` at the bottom right of the screen, as shown in the image.
    * Make sure that you have the entire repo open on VS Code and not just the individual files.
    * If this is your first time installing LiveServer, you might need to close/quit VS Code and reopen it.
* Test it out, and see what your HTML page looks like! *It's OK if it's boring, so feel free to style it with CSS!*

</details>

- [ ] Create & Reference `index.js` in `index.html`

<details>
<summary>:question: How do I reference index.js in index.html?</summary>

Put it **at the very end of the body tag!**
```html   
    <script src="index.js" type="text/javascript"></script>
```

</details>

## Writing the Event Handler Function!
On websites, there are many different types of events that can occur. For example:
- The user selects a certain element or hovers the cursor over a certain element.
- The user chooses a key on the keyboard.
- A form is submitted.
- Curious for more? Look [here](https://www.w3schools.com/js/js_events.asp)

We need to create a function which triggers when someone **submits an image**,
but first we will create a function which changes content on the page when we 
submit text.

<details>
<summary>I'm confused on how to do this</summary>

- In your html file, give your form an id

- Change the last input from type ="button" to type = "submit"

```js
 <input value="Submit" type="submit" />
```

- In index.js, create a variable using the id you just created:
   
```js
const bunnForm = document.getElementById('bunnForm');
```
- In your index.js file, create an event listener with an anonymous function.
Inside of the function, create a variable for the value that was input in 
the text box.
   
 ```js
bunnForm.addEventListener('submit', function (event) {
   const username = document.getElementById("username").value
});
```
   
> :bulb: We are retrieving the value of the "username" text box with this code!
> :bulb: The document.getElementById() method gets the value of the input text from the HTML.

- Create a variable to target html div with the id of "output" and use the 
textContent property to add a "❤" to the value that was input for username.

- :bulb: By default, the website will reload whenever a user presses submit. This leads to our text on the page that we set being cleared away. We can prevent this by adding this to the top of our function.

```js
event.preventDefault()
```
   
```js
bunnForm.addEventListener('submit', function (event) {
   event.preventDefault()
   const username = document.getElementById("username").value
   const output = document.getElementById("output")
   output.textContent = username + "❤"
});
```

</details>

## How do I trigger the function when the form is submitted?

The event listener triggers the JavaScript function when the form is submitted.
Here is how the form should look in the bunnimage index.html file:

```html
<form id="bunnForm">
   <label for="name">Code: </label> <br>
   <input type="text" id="username" name="name" aria-label="name" /> <br>
   <input value="Submit" type="submit" />
</form>
<br/>
<div id="output"></div>
```

Here is the JavaScript which should be in a separate JavaScript file index.js:

```js
const bunnForm = document.getElementById('bunnForm');

bunnForm.addEventListener('submit', function (event) {
   event.preventDefault()
   const username = document.getElementById("username").value
   const output = document.getElementById("output")
   output.textContent = username + "❤"
});
```
> 💡 the `for` attribute in the `<label>` and the `aria-label` attribute in the `<input>`element make the website more accessible to users needing assistive technologies such as screen readers.
