### ISSUE TITLE
Week 4: Ultimate CAT INVASION!

### ISSUE THREAD

**Issue by ganning127** [ganning127/test235#2]
Week 4 Step 7 ⬤⬤⬤⬤⬤⬤⬤ | 🕐 Estimated completion: 5-20 minutes

#### Demo: [🐱](https://week4step7.emilychen10.repl.co/)
*It's now time to connect everything together! (catzapp/index.html, catzapp/script.js, and your Azure function)*

<p align="center">
   <img src="https://user-images.githubusercontent.com/69332964/121592570-dd859380-ca08-11eb-8b27-ff6e5ee3008b.gif" width="500" height="300" />
</p>

### ✅  Task:
- [ ] Make sure you're on the `twocatz-frontend` branch
- [ ] Create 4 input boxes to accept 4 names, each with an `id` of `name1`, `name2`, `name3`, and `name4` respectively
- [ ] Modify `catzapp/script.js` so that it calls your Azure Function with the 4 names as parameters
- [ ] Create 4 `img` tags, each with an `id` of `image1`, `image2`, `image3`, and `image4` respectively
- [ ] Display the outputs of the Azure Function as images in the tags
- [ ] Commit your updated changes to `catzapp/index.html` and `catzapp/script.js`

> :bulb: If your test doesn't pass the first time, it might be because your Azure Function is slow to respond. Simply re-run the job like [this](https://github.com/bitprj/Intro-To-Serverless/blob/main/GETTING_STARTED.md#question-do-i-have-to-push-a-commit-to-run-a-check).

### 🚧 Test your Work
Open up your LiveServer plugin and start your local server. **To test your web app:**

⚠️ When you enter FOUR NAMES into each of the text boxes, do FOUR CAT PICTURES show up below?

### How can Base64 turn into a Cat?
Now that you should've received strings of `base64` from your Azure function call, you need some way to display them for the users. 

<details>
<summary>:question: How can I display base64?</summary>
  </br>

:one: Retrieve the base64 values from your API

:two: Append `data:image/png;base64,` in front of the base64 data

:three: Like you've done previously, modify the `src` attribute of the image tags and set it equal to the string you created in :two:

Read more [here](https://www.w3docs.com/snippets/html/how-to-display-base64-images-in-html.html)
  <br><br/>
</details>
