### ISSUE TITLE
Week 1: Say Hello to VSCode

### ISSUE THREAD

**Issue by ganning127** [ganning127/test235#4]
Week 1 Step 2 ⬤⬤◯◯◯◯◯◯◯ | 🕐 Estimated completion: 5-20 minutes

# Say "Hello" to VS Code

## ✅  Tasks:
- [ ] ***1:*** Download Visual Studio Code and install the **Azure Tools** and **Live Server** extensions
- [ ] ***2:*** Clone this repo using the terminal on VS Code and create a new branch named `hello`
- [ ] ***3:*** In a new file called `week1/helloworld.js`, write and export a JS function `hello` that returns "Hello World"
- [ ] 🚀 Commit your changes to the `hello` branch move on
- [ ] 🚀 Create a pull request that merges `hello` to `main`, but **do not merge it** -- you will find the next step once you have successfully created the pull request and committed correct code

:bulb: **Tip**: When we tell you to name a file called `directory/thefile.js`, the first part before the `/` is a directory (otherwise known as a folder).

## 🚧 Test your Work
If you run `node helloworld.js` in the terminal, the output should be `Hello World`

*Note: From now on, you will never need to close an issue. The Counselor will do that for you, create new issues, and new comments for further instructions!*

### :x: My code failed, what do I do?
No worries, check [this out](https://github.com/bitprj/Intro-To-Serverless/blob/main/GETTING_STARTED.md#x-the-step-failed-what-do-i-do) to help resolve the issue.

> :bulb: **TIP:** If you want to re-run a check without comitting something else, check [this out.](https://github.com/bitprj/Intro-To-Serverless/blob/main/GETTING_STARTED.md#question-do-i-have-to-push-a-commit-to-run-a-check)

## 1: The IDE - Visual Studio Code
An IDE is a software application that provides comprehensive facilities to computer programmers for software development. An IDE normally consists of at least a source code editor, build automation tools, and a debugger. Although there are hundreds of IDEs to choose from, we are going to use Visual Studio Code due to its popularity and integration with Azure (via extensions and libraries).

<details>
<summary>:computer: How to set up your VS Code Environment</summary>
  </br>

[Download VS Code](https://code.visualstudio.com/download) for your operating system and check out this <a href="https://www.youtube.com/watch?v=VqCgcpAypFQ">tutorial</a> before getting started.

Inside VS Code, download the following extensions:
- Azure Tools (includes Azure Account, Azure App Service, Azure Functions)
- Live Server

All of the Azure extensions allow you to work on your Azure Function App in VS Code instead of working directly through the Microsoft portal. Live Server is a quick and temporary testing server, and you can use it to test HTML pages. To launch, right click on your html file and press "Open with Live Server" or click "Go Live" in the bottom right corner:

<img width="552" alt="Screen Shot 2021-01-10 at 1 53 20 PM" src="https://user-images.githubusercontent.com/70852990/104403390-6cf44c80-5526-11eb-8274-0a73f0840954.png">
<img width="552" alt="Screen Shot 2021-01-10 at 1 53 40 PM" src="https://user-images.githubusercontent.com/70852990/104403466-93b28300-5526-11eb-8534-34e408a5d600.png">
<br></br>
</details>

> Note: Dark Theme is our personal favorite, but feel free to choose whichever theme you like best. Go to [this site](https://code.visualstudio.com/docs/getstarted/themes) to view your options!

## 2: GitHub with VS Code

Check out this awesome documentation about [how to set up Git on your local computer](https://docs.github.com/en/github/getting-started-with-github/set-up-git) 

<details>
  <summary>:exclamation: How do I use GitHub on VS Code?</summary>
  
  1. Once you have complete the steps in the documentation, clone this repo on your computer 
  2. Use the following commands to work with branches in the terminal:
  - Check which branch you're in: `git branch` 
  - Create a new branch and change into it: `git checkout --b name-of-branch` 
  - Change branch: `git checkout name-of-branch` 
  3. Afterwards, follow [this tutorial](https://code.visualstudio.com/docs/editor/github) by VS Code on connecting to GitHub straight from the app!

</details>

:exclamation: *Don't forget to `git pull` before making any changes to your local repo!!*

## 3: Writing and Exporting a Javascript function

JavaScript enables the ability to [export functions](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export) in a program so that you can access them in other parts of the program via the import statement. In this case, we want to export your programs in order for CounselorBot to check your code.

<details>
<summary>:question: What are JavaScript and Node?</summary>
</br>
Javascript is the language of the internet! It is a powerful tool for creating complex web apps. However, JavaScript can be used for building the client for applications, and sometimes requires a way to access this client, which is also known as the server-side. Node.js is the solution to this problem, and allows you to write and run code not linked to a website locally.

:exclamation: Make sure you have Node.js and npm installed before moving forwards: https://www.npmjs.com/get-npm
* Check if node is installed: run `node -v` in your terminal
* Check if npm is installed: run `npm -v` in your terminal

If you would like to read more, refer to [this article](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript) on JavaScript and [this article](https://www.tutorialspoint.com/nodejs/nodejs_introduction.htm) on Node.
<br><br/>
</details>

<details>
<summary>:question: How do I export a function?</summary>
</br>
Let's say your function name is `hello`. To export it, add this line of code at the very bottom of your file outside of your function: `module.exports = hello`.

Example:

```js
function hello() {
    // your code
} 

module.exports = hello
```

When you commit the file, we will try to run the function by importing it and compare it's output to the expected output like so:

```js
let hello = require('../../week1/helloworld.js')
let output = hello()
```

### How does this apply to code in the real world?
Just like you can import code from modules other people have written, you can also **import functions you wrote from *other files* to reuse them.** In function oriented programming, you use functions over and over again to save code. If you want to use the function `hello()` in another file, you would need to import it.
<br><br/>
</details>

<details>
<summary>:question: Can I have more detailed steps?</summary>
    </br>

1. Create a new file
2. Name the file helloworld.js
3. Write your code
4. If you have node installed on your computer, open terminal on VS Code and type 'node helloworld.js'
5. If you have not installed node on your computer, you will need to do that first: https://nodejs.org/en/download/
6. Tip: to test your function, call it in your code.
7. Create a new branch named `week1` and commit your `helloworld.js` file in the root directory.
<br><br/>
</details>

> :bulb: Try to not use the web editor! Commit from your command line.

## 🚀 Commiting to a repository using a command line?

Start out by [downloading Git](https://git-scm.com/downloads). Then, open your command line.

### The Commands
Navigate to the directory in your command line where you want to keep your repository.

> Tip: Use `cd ./your-directory` to change directories, `pwd` to find out where you are, and `ls` to list files & directories. More information is [here](https://www.earthdatascience.org/courses/intro-to-earth-data-science/open-reproducible-science/bash/bash-commands-to-manage-directories-files/). 

<details>
<summary>Cloning your repository</summary>
Click on "Code" on your repo's page and find your repo's HTTP link:
<br>
<img src="https://user-images.githubusercontent.com/69332964/116948751-53e6e700-ac4e-11eb-821a-23ccca60f046.png" width=300>

Use the `git clone` command **and replace the url** to get your repository's files onto your local computer:
```
git clone https://github.com/example/example.git
```

Now is the time to make your changes to your code!
</details>

<br>

<details>
<summary>Committing and pushing code</summary>
First, "stage" your changes. You will be specifying what files you want to commit the changes of.

Stage `helloworld.js` changes only:
```
git add helloworld.js
```

Stage ALL your changes to the repository:
```
git add *
```

Next, let's commit the code. Usually, your commits will be a group of changes that make sense together. *Add a description!*
```
git commit -m "insert your description"
```

Save your commits to the repository on Github!
```
git push
```

**For more information, refer to [this link](https://docs.github.com/en/github/managing-files-in-a-repository/adding-a-file-to-a-repository-using-the-command-line)**
</details>
</br>

#### Congrats! Your changes should now be visible on Github
:exclamation: *Don't forget to `git pull` before making any changes to your local repo!!* This gets any changes that were made by the bot.
